### ISSUE TITLE
Firebase Google Login In

### ISSUE THREAD

**Issue by momshaddinury** [dinurymomshad/listify#2]

**Comment by its-me-mahmud** [comment]
@dinurymomshad Update your google-services.json config file. I can't sign in with google because of this reason.

**Comment by momshaddinury** [comment]
@its-me-mahmud Google login isn't implemented yet

**Comment by its-me-mahmud** [comment]
I've implemented already that's why asked you to update the above file and enable the google sign in from the firebase authentication tab/menu

**Comment by momshaddinury** [comment]
Any PR I can review before I make any changes?
