### ISSUE TITLE
Hey creator I like to make listify more attractive may I? 

### ISSUE THREAD

**Issue by Ramasubramanian-S** [dinurymomshad/listify#40]
@dinurymomshad 
Let's make it awesome

**Comment by momshaddinury** [comment]
Hello,
Thanks for contacting me. What do you have in mind?

**Comment by Ramasubramanian-S** [comment]
Please let me to do my first contribution and it will results awesome!
@dinurymomshad

**Comment by Ramasubramanian-S** [comment]
I going to do a small change in code that will make it more meaningful and professional
